
#### Data

This data shows various attributes of rental bikes like the duration, distance, location, date and time driven etc. There are more than 408880 observations in the data. The source of the data is [biketown-tripdata-public](https://s3.amazonaws.com/biketown-tripdata-public/index.html)


#### Purpose

The purpose of the app is to:

1. Compare the average speed of different bikes in a plot. Speed is calculated by dividing distance driven by duration driven. 
2. Using latitude and longitude on one's area, find the common characteristics like payment plan, average duration and average speed driven when users start in that area.
3. Intrigue the users about make them guess which time of the day is most common for riders and also giving information and the right answer. 

The first two aspects of the app are to give users basic insight that they can use while renting the bikes. When users are asked to guess about the time without showing the actual answer is interest them more which is what the third part of the app aims to do. 

#### Creator

Sneha Kharbanda (sneha.kharbanda@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
